---
abstract: 'Change and print terminal line settings'
author:
  - 'Austin Schutz <auschutz@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IO-Stty
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
resources:
  bugtracker: http://github.com/toddr/IO-Stty/issues
  homepage: http://wiki.github.com/toddr/IO-Stty
  license: http://dev.perl.org/licenses/
  repository: http://github.com/toddr/IO-Stty
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
